# Arrow Count
scoreboard players set @a item_count:arrow 0
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=1}] item_count:arrow 1
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=2}] item_count:arrow 2
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=3}] item_count:arrow 3
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=4}] item_count:arrow 4
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=5}] item_count:arrow 5
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=6}] item_count:arrow 6
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=7}] item_count:arrow 7
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=8}] item_count:arrow 8
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=9}] item_count:arrow 9
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=10}] item_count:arrow 10
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=11}] item_count:arrow 11
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=12}] item_count:arrow 12
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=13}] item_count:arrow 13
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=14}] item_count:arrow 14
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=15}] item_count:arrow 15
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=16}] item_count:arrow 16
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=17}] item_count:arrow 17
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=18}] item_count:arrow 18
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=19}] item_count:arrow 19
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=20}] item_count:arrow 20
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=21}] item_count:arrow 21
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=22}] item_count:arrow 22
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=23}] item_count:arrow 23
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=24}] item_count:arrow 24
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=25}] item_count:arrow 25
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=26}] item_count:arrow 26
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=27}] item_count:arrow 27
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=28}] item_count:arrow 28
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=29}] item_count:arrow 29
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=30}] item_count:arrow 30
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=31}] item_count:arrow 31
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=32}] item_count:arrow 32
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=33}] item_count:arrow 33
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=34}] item_count:arrow 34
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=35}] item_count:arrow 35
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=36}] item_count:arrow 36
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=37}] item_count:arrow 37
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=38}] item_count:arrow 38
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=39}] item_count:arrow 39
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=40}] item_count:arrow 40
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=41}] item_count:arrow 41
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=42}] item_count:arrow 42
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=43}] item_count:arrow 43
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=44}] item_count:arrow 44
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=45}] item_count:arrow 45
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=46}] item_count:arrow 46
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=47}] item_count:arrow 47
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=48}] item_count:arrow 48
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=49}] item_count:arrow 49
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=50}] item_count:arrow 50
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=51}] item_count:arrow 51
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=52}] item_count:arrow 52
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=53}] item_count:arrow 53
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=54}] item_count:arrow 54
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=55}] item_count:arrow 55
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=56}] item_count:arrow 56
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=57}] item_count:arrow 57
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=58}] item_count:arrow 58
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=59}] item_count:arrow 59
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=60}] item_count:arrow 60
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=61}] item_count:arrow 61
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=62}] item_count:arrow 62
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=63}] item_count:arrow 63
scoreboard players add @a[hasitem={item=arrow, location=slot.weapon.offhand, quantity=64}] item_count:arrow 64

# Firework Rocket Count
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=1}] item_count:firework_rocket 1
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=2}] item_count:firework_rocket 2
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=3}] item_count:firework_rocket 3
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=4}] item_count:firework_rocket 4
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=5}] item_count:firework_rocket 5
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=6}] item_count:firework_rocket 6
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=7}] item_count:firework_rocket 7
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=8}] item_count:firework_rocket 8
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=9}] item_count:firework_rocket 9
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=10}] item_count:firework_rocket 10
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=11}] item_count:firework_rocket 11
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=12}] item_count:firework_rocket 12
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=13}] item_count:firework_rocket 13
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=14}] item_count:firework_rocket 14
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=15}] item_count:firework_rocket 15
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=16}] item_count:firework_rocket 16
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=17}] item_count:firework_rocket 17
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=18}] item_count:firework_rocket 18
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=19}] item_count:firework_rocket 19
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=20}] item_count:firework_rocket 20
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=21}] item_count:firework_rocket 21
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=22}] item_count:firework_rocket 22
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=23}] item_count:firework_rocket 23
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=24}] item_count:firework_rocket 24
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=25}] item_count:firework_rocket 25
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=26}] item_count:firework_rocket 26
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=27}] item_count:firework_rocket 27
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=28}] item_count:firework_rocket 28
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=29}] item_count:firework_rocket 29
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=30}] item_count:firework_rocket 30
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=31}] item_count:firework_rocket 31
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=32}] item_count:firework_rocket 32
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=33}] item_count:firework_rocket 33
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=34}] item_count:firework_rocket 34
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=35}] item_count:firework_rocket 35
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=36}] item_count:firework_rocket 36
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=37}] item_count:firework_rocket 37
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=38}] item_count:firework_rocket 38
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=39}] item_count:firework_rocket 39
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=40}] item_count:firework_rocket 40
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=41}] item_count:firework_rocket 41
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=42}] item_count:firework_rocket 42
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=43}] item_count:firework_rocket 43
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=44}] item_count:firework_rocket 44
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=45}] item_count:firework_rocket 45
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=46}] item_count:firework_rocket 46
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=47}] item_count:firework_rocket 47
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=48}] item_count:firework_rocket 48
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=49}] item_count:firework_rocket 49
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=50}] item_count:firework_rocket 50
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=51}] item_count:firework_rocket 51
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=52}] item_count:firework_rocket 52
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=53}] item_count:firework_rocket 53
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=54}] item_count:firework_rocket 54
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=55}] item_count:firework_rocket 55
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=56}] item_count:firework_rocket 56
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=57}] item_count:firework_rocket 57
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=58}] item_count:firework_rocket 58
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=59}] item_count:firework_rocket 59
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=60}] item_count:firework_rocket 60
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=61}] item_count:firework_rocket 61
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=62}] item_count:firework_rocket 62
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=63}] item_count:firework_rocket 63
scoreboard players set @a[hasitem={item=firework_rocket, location=slot.weapon.offhand, quantity=64}] item_count:firework_rocket 64

# Nautilus Shell Count
scoreboard players set @a item_count:nautilus_shell 0
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=1}] item_count:nautilus_shell 1
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=2}] item_count:nautilus_shell 2
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=3}] item_count:nautilus_shell 3
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=4}] item_count:nautilus_shell 4
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=5}] item_count:nautilus_shell 5
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=6}] item_count:nautilus_shell 6
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=7}] item_count:nautilus_shell 7
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=8}] item_count:nautilus_shell 8
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=9}] item_count:nautilus_shell 9
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=10}] item_count:nautilus_shell 10
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=11}] item_count:nautilus_shell 11
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=12}] item_count:nautilus_shell 12
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=13}] item_count:nautilus_shell 13
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=14}] item_count:nautilus_shell 14
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=15}] item_count:nautilus_shell 15
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=16}] item_count:nautilus_shell 16
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=17}] item_count:nautilus_shell 17
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=18}] item_count:nautilus_shell 18
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=19}] item_count:nautilus_shell 19
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=20}] item_count:nautilus_shell 20
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=21}] item_count:nautilus_shell 21
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=22}] item_count:nautilus_shell 22
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=23}] item_count:nautilus_shell 23
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=24}] item_count:nautilus_shell 24
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=25}] item_count:nautilus_shell 25
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=26}] item_count:nautilus_shell 26
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=27}] item_count:nautilus_shell 27
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=28}] item_count:nautilus_shell 28
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=29}] item_count:nautilus_shell 29
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=30}] item_count:nautilus_shell 30
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=31}] item_count:nautilus_shell 31
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=32}] item_count:nautilus_shell 32
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=33}] item_count:nautilus_shell 33
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=34}] item_count:nautilus_shell 34
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=35}] item_count:nautilus_shell 35
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=36}] item_count:nautilus_shell 36
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=37}] item_count:nautilus_shell 37
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=38}] item_count:nautilus_shell 38
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=39}] item_count:nautilus_shell 39
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=40}] item_count:nautilus_shell 40
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=41}] item_count:nautilus_shell 41
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=42}] item_count:nautilus_shell 42
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=43}] item_count:nautilus_shell 43
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=44}] item_count:nautilus_shell 44
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=45}] item_count:nautilus_shell 45
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=46}] item_count:nautilus_shell 46
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=47}] item_count:nautilus_shell 47
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=48}] item_count:nautilus_shell 48
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=49}] item_count:nautilus_shell 49
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=50}] item_count:nautilus_shell 50
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=51}] item_count:nautilus_shell 51
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=52}] item_count:nautilus_shell 52
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=53}] item_count:nautilus_shell 53
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=54}] item_count:nautilus_shell 54
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=55}] item_count:nautilus_shell 55
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=56}] item_count:nautilus_shell 56
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=57}] item_count:nautilus_shell 57
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=58}] item_count:nautilus_shell 58
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=59}] item_count:nautilus_shell 59
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=60}] item_count:nautilus_shell 60
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=61}] item_count:nautilus_shell 61
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=62}] item_count:nautilus_shell 62
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=63}] item_count:nautilus_shell 63
scoreboard players add @a[hasitem={item=nautilus_shell, location=slot.weapon.offhand, quantity=64}] item_count:nautilus_shell 64